# Generated by Django 2.2.3 on 2020-09-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_total',
        ),
    ]
